# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       tor

# >> macros
# << macros
%define custom_vardir /home/.system/%{_var}

Summary:    Anonymizing overlay network for TCP
Version:    0.4.7.10
Release:    0
Group:      Applications/Internet
License:    GPLv2 and BSD
URL:        https://www.torproject.org
Source0:    %{name}-%{version}.tar.gz
Source1:    %{name}.service
Source2:    torrc.minimal
Source100:  tor.yaml
Source101:  tor-rpmlintrc
Requires:   systemd
Requires(post): systemd
Requires(postun): systemd
BuildRequires:  pkgconfig(libevent)
BuildRequires:  pkgconfig(libssl)
BuildRequires:  pkgconfig(systemd)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  pkgconfig(libzstd)
BuildRequires:  qt5-qmake
BuildRequires:  sailfish-svg2png

%description
Tor (or The Onion Router) is a free software for enabling online anonymity. Tor
directs Internet traffic through a free, worldwide, volunteer network
consisting of more than four thousand relays to conceal a user's location or
usage from anyone conducting network surveillance or traffic analysis.

Notices for SailfishOS:
  the config lives in `/home/.system/var/lib/tor`, not `/etc`

%if "%{?vendor}" == "chum"
PackageName: Tor
Type: console-application
PackagerName: nephros
Categories:
 - Network
 - P2P
Custom:
  Repo: %{url}
  PackagingRepo: https://github.com/nephros/tor
Icon: %{url}/static/images/tor-logo.svg
Url:
  Homepage: %{url}
  Donations:
    - https://donate.torproject.org/
%endif


%package ui
Summary:    UI components for %{name}
License:    ASL 2.0 and Public Domain
Group:      Applications/Internet
BuildArch:  noarch
Requires:   %{name}
Requires:   jolla-settings

%description ui
Settings UI integration for Tor.

Adds a Settings entry and a TopMenu switch to start/stop the demon
and show some state information.
Installing this will install the daemon as well.

Tor (or The Onion Router) is a free software for enabling online anonymity. Tor
directs Internet traffic through a free, worldwide, volunteer network
consisting of more than four thousand relays to conceal a user's location or
usage from anyone conducting network surveillance or traffic analysis.

%if "%{?vendor}" == "chum"
PackageName: Tor Settings UI
Type: desktop-application
PackagerName: nephros
Categories:
 - Network
 - P2P
Custom:
  Repo: https://github.com/nephros/tor
Icon: %{url}/static/images/tor-logo.svg
%endif


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%reconfigure --disable-static \
    --disable-all-bugs-are-fatal \
    --disable-android \
    --disable-asciidoc \
    --disable-manpage \
    --disable-html-manual \
    --disable-libfuzzer \
    --disable-missing-doc-warnings \
    --disable-module-dirauth \
    --disable-module-relay \
    --disable-restart-debugging \
    --disable-zstd-advanced-apis \
    --disable-gcc-warnings-advisory \
    --enable-pic \
    --enable-systemd \
    --disable-lzma \
    --enable-zstd \
    --disable-system-torrc \
    --localstatedir=%{custom_vardir}

make %{?_smp_mflags}

# >> build post

## UI:
pushd %{_builddir}/%{name}-%{version}
%qmake5
%qmake5_install
popd
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
install -D -m644 %SOURCE1 %{buildroot}/%{_unitdir}/%{name}.service
install -D -m644 %SOURCE2 %{buildroot}/%{custom_vardir}/lib/%{name}/torrc
# << install post

%preun
# >> preun
%systemd_preun %{name}.service
# << preun

%post
# >> post
%systemd_post %{name}.service
# << post

%postun
# >> postun
%systemd_postun_with_restart %{name}.service
# << postun

%files
%defattr(-,root,root,-)
%license LICENSE
%{_bindir}/*
%dir %{custom_vardir}/lib/%{name}
%config(noreplace) %{custom_vardir}/lib/%{name}/torrc
%dir %{_sysconfdir}/%{name}
%exclude %{_sysconfdir}/%{name}*
%{_datadir}/%{name}/*
%{_unitdir}/%{name}.service
# >> files
# << files

%files ui
%defattr(-,root,root,-)
%{_datadir}/jolla-settings/entries/i2pd.json
%{_datadir}/jolla-settings/pages/i2p/*
%{_datadir}/themes/*/meegotouch/*/icons/*
%{_datadir}/icons/hicolor/scalable/apps/*.svg
# >> files ui
# << files ui
